[package]
name = "cognito-jwt"
version = "0.1.0-alpha.1"
authors = ["Robert Bragg <robert@sixbynine.org>"]
edition = "2018"
repository = "https://github.com/rib/cognito-jwt"
documentation = "https://docs.rs/cognito-jwt/"
readme = "README.md"
license = "MIT"
keywords = ["jwt", "token", "jwk", "jwks", "web", "api", "cognito"]
categories = ["authentication"]
description = "Decodes and verifies Json Web Tokens issued by AWS Cognito"

[dependencies]
jwt-rust = { git = "https://github.com/rib/jwt-rust" }
reqwest = { git = "https://github.com/seanmonstar/reqwest", features=["json"] }
serde = { version="1", features=["derive"] }
serde_json = "1"
